# Operating system (build VM template)
os: Visual Studio 2015

# clone directory
clone_folder: c:\projects\journey

platform:
  - win32
  - x64

configuration:
  - Release

environment:
  matrix:
  - buildType: win32
    fullBuildType: windows32
    generatorName: Visual Studio 14
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  - buildType: win64
    fullBuildType: windows64
    generatorName: Visual Studio 14 Win64
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  exclude:
    - platform: x64
      buildType: win32
    - platform: win32
      buildType: win64

before_build:
  - cd c:\projects\journey && setup_native_windows.bat

after_build:
  - cd c:\projects\journey && build_native_windows.bat
  - cd c:\projects\journey && gradlew.bat build -x test

artifacts:
  - path: jcef\binary_distrib\jcef-distrib-%fullBuildType%.zip
    name: jcef-distrib-%fullBuildType%

deploy:
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: Dta1mWx33cdacZT+HJzfI0I9aauuITU8bbHzCg7F7i9nL0UpE+ZsTXzbKbGWd8gy
  artifact: jcef\binary_distrib\jcef-distrib-%fullBuildType%.zip
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
